services:
  app:
    container_name: app
    build: ./webapp/
    restart: on-failure
    env_file:
      - ./webapp/.env
    environment:
      "SQLALCHEMY_DATABASE_URI": postgresql://user:password@postgres/db
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  mongo:
    image: mongo:6.0.6-jammy
    container_name: mongo
    hostname: mongo
    restart: always
    env_file:
      - ./mongo/.env-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./mongo/.env-mongo-express

  postgres:
    container_name: postgres
    image: postgres:15.3-bookworm
    env_file:
      - ./postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/sql:/docker-entrypoint-initdb.d
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "shared_buffers=1GB"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  mongo:
  postgres:
