services:
  db:
    container_name: event_db
    image: postgres:14.3-bullseye
    restart: on-failure
    env_file:
      - ./server/db/.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
#      - ./server/db/sql_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d events" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  server:
    build: ./server/
    restart: always
    env_file:
      - ./server/.env
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.22.0
    container_name: nginx
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./server/webapp/static/:/static
    ports:
      - 80:80
    depends_on:
      - server

volumes:
  db:
