"""updated event model and views

Revision ID: 2822c932a43a
Revises: 80b1c0135886
Create Date: 2021-07-13 00:46:15.303961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2822c932a43a'
down_revision = '80b1c0135886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_creator_id'), 'event', ['creator_id'], unique=False)
    op.create_index(op.f('ix_event_creator_login'), 'event', ['creator_login'], unique=False)
    op.drop_constraint('event_creator_id_fkey', 'event', type_='foreignkey')
    op.drop_constraint('event_creator_login_fkey', 'event', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('event_creator_login_fkey', 'event', 'user', ['creator_login'], ['login'])
    op.create_foreign_key('event_creator_id_fkey', 'event', 'user', ['creator_id'], ['id'])
    op.drop_index(op.f('ix_event_creator_login'), table_name='event')
    op.drop_index(op.f('ix_event_creator_id'), table_name='event')
    # ### end Alembic commands ###
