"""first migrate

Revision ID: 14ea0a0085b6
Revises: 
Create Date: 2021-07-10 00:23:32.931071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ea0a0085b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('creator_login', sa.String(), nullable=False))
    op.add_column('event', sa.Column('header', sa.String(), nullable=False))
    op.add_column('event', sa.Column('second_header', sa.String(), nullable=True))
    op.add_column('event', sa.Column('url', sa.String(), nullable=True))
    op.add_column('event', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('event', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('event', sa.Column('contacs', sa.String(), nullable=True))
    op.alter_column('event', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'event', 'user', ['creator_login'], ['login'])
    op.drop_column('event', 'contacts')
    op.drop_column('event', 'event_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('contacts', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.alter_column('event', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('event', 'contacs')
    op.drop_column('event', 'avatar')
    op.drop_column('event', 'description')
    op.drop_column('event', 'url')
    op.drop_column('event', 'second_header')
    op.drop_column('event', 'header')
    op.drop_column('event', 'creator_login')
    # ### end Alembic commands ###
