"""init db

Revision ID: 4290275517e8
Revises:
Create Date: 2022-06-26 13:17:52.625307

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4290275517e8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("creator_login", sa.Integer(), nullable=True),
        sa.Column("header", sa.String(), nullable=False),
        sa.Column("second_header", sa.String(), nullable=True),
        sa.Column("event_url", sa.String(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("contacts", sa.String(), nullable=True),
        sa.Column("start_date", sa.String(), nullable=True),
        sa.Column("end_date", sa.String(), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.Column("party", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_address"), "event", ["address"], unique=False)
    op.create_index(op.f("ix_event_creator_id"), "event", ["creator_id"], unique=False)
    op.create_index(
        op.f("ix_event_creator_login"), "event", ["creator_login"], unique=False
    )
    op.create_index(op.f("ix_event_header"), "event", ["header"], unique=False)
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tag_tag"), "tag", ["tag"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("login", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("path_to_avatar", sa.String(), nullable=True),
        sa.Column("role", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_user_login"), "user", ["login"], unique=True)
    op.create_index(op.f("ix_user_role"), "user", ["role"], unique=False)
    op.create_table(
        "event_tags",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "tag_id"),
    )
    op.create_table(
        "user_tags",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_tags")
    op.drop_table("event_tags")
    op.drop_index(op.f("ix_user_role"), table_name="user")
    op.drop_index(op.f("ix_user_login"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_tag_tag"), table_name="tag")
    op.drop_table("tag")
    op.drop_index(op.f("ix_event_header"), table_name="event")
    op.drop_index(op.f("ix_event_creator_login"), table_name="event")
    op.drop_index(op.f("ix_event_creator_id"), table_name="event")
    op.drop_index(op.f("ix_event_address"), table_name="event")
    op.drop_table("event")
    # ### end Alembic commands ###
