"""updated event model, form and views

Revision ID: 80b1c0135886
Revises: fb18f67b4d1a
Create Date: 2021-07-13 00:11:43.376892

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "80b1c0135886"
down_revision = "fb18f67b4d1a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("start_date", sa.String(), nullable=True))
    op.add_column("event", sa.Column("end_date", sa.String(), nullable=True))
    op.add_column("event", sa.Column("party", sa.String(), nullable=True))
    op.alter_column("event", "creator_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("event", "creator_login", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index("ix_event_create_date", table_name="event")
    op.drop_index("ix_event_creator_id", table_name="event")
    op.drop_index("ix_event_creator_login", table_name="event")
    op.drop_column("event", "date_end")
    op.drop_column("event", "date_start")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event",
        sa.Column(
            "date_start", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "event",
        sa.Column(
            "date_end", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.create_index("ix_event_creator_login", "event", ["creator_login"], unique=False)
    op.create_index("ix_event_creator_id", "event", ["creator_id"], unique=False)
    op.create_index("ix_event_create_date", "event", ["create_date"], unique=False)
    op.alter_column(
        "event", "creator_login", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("event", "creator_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("event", "party")
    op.drop_column("event", "end_date")
    op.drop_column("event", "start_date")
    # ### end Alembic commands ###
