"""fixed Event model

Revision ID: fb18f67b4d1a
Revises: 14ea0a0085b6
Create Date: 2021-07-11 17:21:22.122615

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fb18f67b4d1a"
down_revision = "14ea0a0085b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("creator_login", sa.String(), nullable=False))
    op.add_column("event", sa.Column("header", sa.String(), nullable=False))
    op.add_column("event", sa.Column("second_header", sa.String(), nullable=True))
    op.add_column("event", sa.Column("event_url", sa.String(), nullable=True))
    op.add_column("event", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("event", sa.Column("avatar_url", sa.String(), nullable=True))
    op.add_column("event", sa.Column("contacs", sa.String(), nullable=True))
    op.add_column("event", sa.Column("date_start", sa.DateTime(), nullable=True))
    op.add_column("event", sa.Column("date_end", sa.DateTime(), nullable=True))
    op.alter_column("event", "address", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_event_address"), "event", ["address"], unique=False)
    op.create_index(
        op.f("ix_event_create_date"), "event", ["create_date"], unique=False
    )
    op.create_index(op.f("ix_event_creator_id"), "event", ["creator_id"], unique=False)
    op.create_index(
        op.f("ix_event_creator_login"), "event", ["creator_login"], unique=False
    )
    op.create_index(op.f("ix_event_header"), "event", ["header"], unique=False)
    op.create_foreign_key(None, "event", "user", ["creator_login"], ["login"])
    op.drop_column("event", "path_to_avatar")
    op.drop_column("event", "contacts")
    op.drop_column("event", "event_name")
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.add_column(
        "event",
        sa.Column("event_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "event", sa.Column("contacts", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "event",
        sa.Column("path_to_avatar", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "event", type_="foreignkey")
    op.drop_index(op.f("ix_event_header"), table_name="event")
    op.drop_index(op.f("ix_event_creator_login"), table_name="event")
    op.drop_index(op.f("ix_event_creator_id"), table_name="event")
    op.drop_index(op.f("ix_event_create_date"), table_name="event")
    op.drop_index(op.f("ix_event_address"), table_name="event")
    op.alter_column("event", "address", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("event", "date_end")
    op.drop_column("event", "date_start")
    op.drop_column("event", "contacs")
    op.drop_column("event", "avatar_url")
    op.drop_column("event", "description")
    op.drop_column("event", "event_url")
    op.drop_column("event", "second_header")
    op.drop_column("event", "header")
    op.drop_column("event", "creator_login")
    # ### end Alembic commands ###
