"""added balloonContent in MongoDB

Revision ID: fe39345a6924
Revises: 2822c932a43a
Create Date: 2021-07-14 22:45:16.330762

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fe39345a6924"
down_revision = "2822c932a43a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "description")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event", sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
